# Website details
name: WALL-E
description: 我的经历，感受和想法
email: i@lizhe.me
author: Zhe
lang: zh
locale: zh_CN

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: GMT
#avoid any conversion. America/New_York
paginateLabel: page
paginate_path: "page/:num"
permalink: pretty
baseurl: https://moongazer.me

# Includes
addthisId: ""
disqusUsername: "zooeyg"
googleAnalyticsId: "UA-72170476-4"

# Search engine verifications
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
